import { StyleSheet } from "react-native";
import { Palette } from "../constants/palette";

export const makeLoginStyles = (c: Palette) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.loginBg,
      padding: 24,
      justifyContent: "center",
    },
    title: {
      fontFamily: "BebasNeue",
      fontSize: 80,
      color: c.logoText,
      fontStyle: "italic",
      lineHeight: 80,
      marginBottom: 32,
      textAlign: "center",
    },
    card: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 24,
      borderWidth: 1,
      borderColor: c.loginBorder,
    },
    cardTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: c.text,
      textAlign: "center",
      marginBottom: 4,
    },
    cardSubtitle: {
      fontSize: 14,
      color: c.textMuted,
      textAlign: "center",
      marginBottom: 8,
    },
    label: {
      fontSize: 11,
      fontWeight: "700",
      color: c.textMuted,
      letterSpacing: 1,
      marginBottom: 8,
    },
    input: {
      backgroundColor: c.input,
      borderWidth: 1,
      borderColor: c.loginBorder,
      borderRadius: 8,
      padding: 16,
      color: c.text,
      marginBottom: 16,
    },
    passwordRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 8,
    },
    forgot: { fontSize: 12, color: c.red, fontWeight: "700" },
    mainButton: {
      backgroundColor: c.red,
      padding: 16,
      borderRadius: 8,
      alignItems: "center",
      marginTop: 8,
    },
    mainButtonText: {
      color: "#FFFFFF",
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 2,
    },
    orRow: { flexDirection: "row", alignItems: "center", marginVertical: 20 },
    line: { flex: 1, height: 1, backgroundColor: c.loginBorder },
    orText: { color: c.textMuted, marginHorizontal: 12, fontSize: 12 },
    socialButton: {
      borderWidth: 1,
      borderColor: c.loginBorder,
      borderRadius: 8,
      padding: 16,
      alignItems: "center",
    },
    socialButtonText: {
      color: c.text,
      fontWeight: "700",
      fontSize: 13,
      letterSpacing: 1,
    },
    signupText: {
      color: c.textMuted,
      textAlign: "center",
      marginTop: 24,
      fontSize: 14,
    },
    signupLink: { color: c.text, fontWeight: "700" },
  });
