import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

export const styles = StyleSheet.create({
  eventTitle: {
    fontFamily: "BebasNeue",
    fontSize: 46,
    color: "#fff",
    letterSpacing: 1,
  },
  eventSub: {
    fontSize: 14,
    color: COLORS.gray,
    marginTop: -2,
    marginBottom: 22,
  },

  mainCard: {
    backgroundColor: "#111111",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#222224",
    marginBottom: 16,
    overflow: "hidden",
  },
  mainHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#161616",
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  mainHeaderText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.5,
    color: "#888",
  },

  fighterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
    marginBottom: 8,
  },
  fighterCol: { alignItems: "center", flex: 1 },
  fighterName: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 18,
    letterSpacing: 1,
    marginTop: 12,
  },
  vs: { color: "#555", fontWeight: "700", fontSize: 16, paddingHorizontal: 8 },

  groupLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.5,
    color: "#666",
    marginTop: 18,
    marginBottom: 10,
  },
  segRow: { flexDirection: "row", gap: 10 },
  seg: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 10,
    backgroundColor: "#181818",
    borderWidth: 1,
    borderColor: "#262626",
    alignItems: "center",
  },
  roundBox: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 10,
    backgroundColor: "#181818",
    borderWidth: 1,
    borderColor: "#262626",
    alignItems: "center",
    justifyContent: "center",
  },
  segActive: { backgroundColor: COLORS.red, borderColor: COLORS.red },
  segText: { color: "#aaa", fontWeight: "700", fontSize: 15, letterSpacing: 1 },
  segTextActive: { color: "#fff" },

  proof: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 20,
    backgroundColor: "#161616",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#242424",
    padding: 14,
  },
  proofAvatars: { flexDirection: "row" },
  proofDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: "#161616",
  },
  proofText: { color: "#ccc", fontSize: 13, flex: 1 },

  rowCard: {
    backgroundColor: "#111111",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#222224",
    padding: 12,
    marginBottom: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
  },
  rowFighter: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  rowName: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.5,
    flexShrink: 1,
  },
  rowNamePicked: { color: COLORS.red },
  rowCenter: {
    alignItems: "center",
    justifyContent: "center",
    width: 84,
    gap: 3,
  },
  rowDivision: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1,
    color: "#666",
  },
  vsSmall: { color: "#555", fontWeight: "700", fontSize: 12 },
  rowBody: {
    marginTop: 12,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: "#222224",
  },

  bottomBar: {
    paddingTop: 10,
    backgroundColor: "#0d0d0d",
    borderTopColor: "#222224",
    borderTopWidth: 1,
  },
  lockWrap: {
    paddingHorizontal: 20,
    paddingBottom: 12,
    borderBottomColor: "#1a1a1a",
    borderBottomWidth: 1,
  },
  lockBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: COLORS.red,
    borderRadius: 12,
    paddingVertical: 16,
  },
  lockBtnDisabled: { opacity: 0.4 },
  lockText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 1.5,
  },
  lockCount: {
    color: "rgba(255,255,255,0.8)",
    fontWeight: "700",
    fontSize: 13,
    marginLeft: 4,
  },

  lockedRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  lockedPill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#1a0d12",
    borderColor: COLORS.red,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 15,
  },
  lockedPillText: {
    color: COLORS.red,
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 1.5,
  },
  changeBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#181818",
    borderColor: "#2a2a2a",
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 15,
  },
  changeBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 1.5,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.92)",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    backgroundColor: "#111111",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#222224",
    padding: 22,
    maxHeight: "92%",
    marginTop: 64,
  },
  modalClose: { position: "absolute", top: 14, right: 14, zIndex: 1 },
  badgeWrap: { alignSelf: "center", marginTop: 8 },
  badge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.red,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeCheck: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#2ecc71",
    borderWidth: 2,
    borderColor: "#111111",
    alignItems: "center",
    justifyContent: "center",
  },
  modalTitle: {
    fontFamily: "BebasNeue",
    fontSize: 38,
    color: "#fff",
    textAlign: "center",
    letterSpacing: 1,
    marginTop: 14,
  },
  modalSub: {
    color: COLORS.gray,
    fontSize: 13,
    textAlign: "center",
    marginTop: 2,
  },
  countdownChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "center",
    backgroundColor: "#181818",
    borderColor: "#2a2a2a",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginTop: 14,
  },
  countdownText: { color: "#ccc", fontSize: 12, fontWeight: "600" },
  summaryCard: {
    backgroundColor: "#161616",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#242424",
    paddingHorizontal: 16,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 13,
  },
  summaryRowBorder: { borderTopWidth: 1, borderTopColor: "#242424" },
  summaryText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  summaryDef: { color: "#777", fontWeight: "400" },
  summaryDetail: { color: "#888", fontSize: 12, marginTop: 2 },
  shareBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: COLORS.red,
    borderRadius: 12,
    paddingVertical: 16,
    marginTop: 20,
  },
  backBtn: {
    alignItems: "center",
    backgroundColor: "#181818",
    borderColor: "#2a2a2a",
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 16,
    marginTop: 10,
  },
  backBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 1.5,
  },
  editLink: { alignItems: "center", marginTop: 14, marginBottom: 4 },
  editLinkText: {
    color: "#888",
    fontSize: 13,
    textDecorationLine: "underline",
  },
});
