import { StyleSheet } from "react-native";
import { Palette } from "../constants/palette";
import { FONTS } from "../constants/type";

export const makePicksStyles = (c: Palette) =>
  StyleSheet.create({
    eventTitle: {
      fontFamily: FONTS.display,
      fontSize: 46,
      color: c.text,
      letterSpacing: 1,
    },
    eventSub: {
      fontSize: 14,
      color: c.textMuted,
      marginTop: -2,
      marginBottom: 22,
    },

    mainCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 16,
      overflow: "hidden",
    },
    mainHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: c.surface2,
      paddingHorizontal: 18,
      paddingVertical: 14,
    },
    mainHeaderText: {
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 1.5,
      color: c.textMuted,
    },

    fighterRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 14,
      marginBottom: 8,
    },
    fighterCol: { alignItems: "center", flex: 1 },
    fighterName: {
      color: c.text,
      fontWeight: "700",
      fontSize: 18,
      letterSpacing: 1,
      marginTop: 12,
    },
    vs: { color: c.textFaint, fontWeight: "700", fontSize: 16, paddingHorizontal: 8 },

    groupLabel: {
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1.5,
      color: c.textFaint,
      marginTop: 18,
      marginBottom: 10,
    },
    segRow: { flexDirection: "row", gap: 10 },
    seg: {
      flex: 1,
      paddingVertical: 16,
      borderRadius: 10,
      backgroundColor: c.input,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
    },
    roundBox: {
      flex: 1,
      aspectRatio: 1,
      borderRadius: 10,
      backgroundColor: c.input,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
    },
    segActive: { backgroundColor: c.red, borderColor: c.red },
    segText: { color: c.text2, fontWeight: "700", fontSize: 15, letterSpacing: 1 },
    segTextActive: { color: "#FFFFFF" },

    proof: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginTop: 20,
      backgroundColor: c.surface2,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 14,
    },
    proofAvatars: { flexDirection: "row" },
    proofDot: {
      width: 26,
      height: 26,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: c.surface2,
    },
    proofText: { color: c.text2, fontSize: 13, flex: 1 },

    rowCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 12,
      marginBottom: 12,
    },
    row: {
      flexDirection: "row",
      alignItems: "center",
    },
    rowFighter: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    rowName: {
      color: c.text,
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.5,
      flexShrink: 1,
    },
    rowNamePicked: { color: c.red },
    rowCenter: {
      alignItems: "center",
      justifyContent: "center",
      width: 84,
      gap: 3,
    },
    rowDivision: {
      fontSize: 9,
      fontWeight: "700",
      letterSpacing: 1,
      color: c.textFaint,
    },
    vsSmall: { color: c.textFaint, fontWeight: "700", fontSize: 12 },
    rowBody: {
      marginTop: 12,
      paddingTop: 4,
      borderTopWidth: 1,
      borderTopColor: c.border,
    },

    bottomBar: {
      paddingTop: 10,
      backgroundColor: c.navBar,
      borderTopColor: c.border,
      borderTopWidth: 1,
    },
    lockWrap: {
      paddingHorizontal: 20,
      paddingBottom: 12,
      borderBottomColor: c.border,
      borderBottomWidth: 1,
    },
    lockBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: c.red,
      borderRadius: 14,
      paddingVertical: 16,
    },
    lockBtnDisabled: { opacity: 0.4 },
    lockText: {
      color: c.onAccent,
      fontWeight: "700",
      fontSize: 15,
      letterSpacing: 1.5,
    },
    lockCount: {
      color: "rgba(255,255,255,0.8)",
      fontWeight: "700",
      fontSize: 13,
      marginLeft: 4,
    },

    lockedRow: { flexDirection: "row", alignItems: "center", gap: 10 },
    lockedPill: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: c.redTint,
      borderColor: c.red,
      borderWidth: 1,
      borderRadius: 14,
      paddingVertical: 15,
    },
    lockedPillText: {
      color: c.red,
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 1.5,
    },
    changeBtn: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.input,
      borderColor: c.borderStrong,
      borderWidth: 1,
      borderRadius: 14,
      paddingVertical: 15,
    },
    changeBtnText: {
      color: c.text,
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 1.5,
    },

    modalOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      justifyContent: "center",
      padding: 16,
    },
    modalCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 22,
      maxHeight: "92%",
      marginTop: 64,
    },
    modalClose: { position: "absolute", top: 14, right: 14, zIndex: 1 },
    badgeWrap: { alignSelf: "center", marginTop: 8 },
    badge: {
      width: 64,
      height: 64,
      borderRadius: 14,
      backgroundColor: c.red,
      alignItems: "center",
      justifyContent: "center",
    },
    badgeCheck: {
      position: "absolute",
      bottom: -2,
      right: -2,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: c.green,
      borderWidth: 2,
      borderColor: c.card,
      alignItems: "center",
      justifyContent: "center",
    },
    modalTitle: {
      fontFamily: FONTS.display,
      fontSize: 38,
      color: c.text,
      textAlign: "center",
      letterSpacing: 1,
      marginTop: 14,
    },
    modalSub: {
      color: c.textMuted,
      fontSize: 13,
      textAlign: "center",
      marginTop: 2,
    },
    countdownChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      alignSelf: "center",
      backgroundColor: c.input,
      borderColor: c.borderStrong,
      borderWidth: 1,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
      marginTop: 14,
    },
    countdownText: { color: c.text2, fontSize: 12, fontWeight: "600" },
    summaryCard: {
      backgroundColor: c.surface2,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      paddingHorizontal: 16,
    },
    summaryRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 13,
    },
    summaryRowBorder: { borderTopWidth: 1, borderTopColor: c.border },
    summaryText: { color: c.text, fontWeight: "700", fontSize: 14 },
    summaryDef: { color: c.textMuted, fontWeight: "400" },
    summaryDetail: { color: c.textMuted, fontSize: 12, marginTop: 2 },
    shareBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: c.red,
      borderRadius: 14,
      paddingVertical: 16,
      marginTop: 20,
    },
    backBtn: {
      alignItems: "center",
      backgroundColor: c.input,
      borderColor: c.borderStrong,
      borderWidth: 1,
      borderRadius: 14,
      paddingVertical: 16,
      marginTop: 10,
    },
    backBtnText: {
      color: c.text,
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 1.5,
    },
    editLink: { alignItems: "center", marginTop: 14, marginBottom: 4 },
    editLinkText: {
      color: c.textMuted,
      fontSize: 13,
      textDecorationLine: "underline",
    },
  });
